exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = blueberry-tray
exec-once = sleep 2 && qs
exec-once = hyprpaper
exec-once = hypridle
# Jalankan portal desktop
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# Menjalankan service clipboard history di background
# exec-once = wl-paste --watch cliphist store
exec-once = walker --gapplication-service
exec-once = hyprctl setcursor Bibata-Modern-Ice 20
# exec-once = /home/fadlullah/.config/waybar/scripts/launch.sh
exec-once = elephant
exec-once = brisk
