ipc = on
splash = false
# preload = /home/fadlullah/Pictures/Wallpapers/arch_windows10_style_wp.png
# wallpaper = ,/home/fadlullah/Pictures/Wallpapers/arch_windows10_style_wp.png

wallpaper {
    monitor = 
    path = /home/fadlullah/Pictures/Wallpapers/arch_windows10_style_wp.png
    fit_mode = cover
}
