
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

misc {
    # If you cycle to a window, and the previous was fullscreen, 
    # this setting can help keep the state when you cycle back.
   on_focus_under_fullscreen = 1
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
windowrule =opacity 1.0 override 1.0 override,size 733 413,center on, float on,match:title ^(Picture-in-Picture)
#windowrule = opacity 1.0 override 1.0 override, title:(.*)(YouTube — Zen Browser|Zoom — Zen Browser)

windowrule = opacity 1.0 override 1.0 override, match:title ((?i).*(YouTube|Meet|Zoom|Ruang Rapat Pribadi|HiAnime.to).*(— Zen Browser))

windowrule = opacity 1.0 override 1.0 override, match:title ((?i).*(YouTube|Meet|Zoom|Ruang Rapat Pribadi|HiAnime.to).*(- Chromium))

# Rules for Wiremix
windowrule = float on , match:class Wiremix
windowrule = center on , match:class Wiremix
windowrule = size (monitor_w*0.45) (monitor_h*0.6), match:class Wiremix
windowrule = float on,match:class ^(blueberry.py)
windowrule = center on,match:class ^(blueberry.py)
windowrule = size (monitor_w*0.3) (monitor_h*0.5),match:class ^(blueberry.py)
windowrule = size 497 102,float on,center on,match:class ^(Thunar),match:title ^(File Operation Progress)
windowrule = size 497 102,float on,center on,match:class ^(Thunar),match:title ^((?i)(Rename).*)
windowrule = size (monitor_w*0.45) (monitor_h*0.6),float on,center on,match:class ^(xdg-desktop-portal-gtk),match:title ^((?i)(Choose a Wallpaper).*)
windowrule = size 700 500 ,float on,center on,match:class ^(org.gnome.FileRoller),match:title ^(Extract)
windowrule = float on, match:class ^(localsend)
windowrule = center on, match:class ^(localsend)
windowrule = size (monitor_w*0.50) (monitor_h*0.65), match:class ^(localsend)
windowrule = float on, match:class ^(web-app-install)
windowrule = center on, match:class ^(web-app-install)
windowrule = size (monitor_w*0.45) (monitor_h*0.6), match:class ^(web-app-install)
windowrule = float on, match:class ^(org.gnome.Calculator)
windowrule = center on, match:class ^(org.gnome.Calculator)
windowrule = float on,match:title ^(Pick Files)
windowrule = float on,match:title ^(Open Files)
windowrule = float on, match:class ^(web-app-remove)
windowrule = center on, match:class ^(web-app-remove)
windowrule = size (monitor_w*0.45) (monitor_h*0.6), match:class ^(web-app-remove)
windowrule = size 497 102,center on,float on,match:class ^(thunar),match:title ^(File Operation Progress)
windowrule = opacity 1.0 override 1.0 override, match:class ^(vlc)
windowrule = size 497 102,float on, float on,center on,match:class ^(thunar),match:title ^((?i)(Rename).*)
windowrule = float on, match:class ^(Impala)
windowrule = center on, match:class ^(Impala)
windowrule = size (monitor_w*0.6) (monitor_h*0.6),match:class ^(Impala)
windowrule = size (monitor_w*0.45) (monitor_h*0.6),float on, center on,  match:class ^(brisk)
windowrule = opacity 1.0 override 1.0 override ,match:class ^(antigravity)

windowrule = size (monitor_w*0.6) (monitor_h*0.6),match:class ^(Open Files)
windowrule = size (monitor_w*0.45) (monitor_h*0.6), center on,float on,match:class ^(Zotero),match:title ^(Add/Edit Citation)
